"""add_summary_to_url

Revision ID: c32f1dfda9ca
Revises: fe97af04811a
Create Date: 2026-05-12 12:19:26.184439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32f1dfda9ca'
down_revision: Union[str, Sequence[str], None] = 'fe97af04811a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'summary')
    # ### end Alembic commands ###
